# Generated by Django 5.2.7 on 2025-11-08 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_TiendadeMagia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='ordendeventa',
            options={'ordering': ['-fecha_orden'], 'verbose_name': 'Orden de Venta', 'verbose_name_plural': 'Órdenes de Venta'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto Mágico', 'verbose_name_plural': 'Productos Mágicos'},
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='ordendeventa',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='ordendeventa',
            name='productos',
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Comprada'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_TiendadeMagia.ordendeventa', verbose_name='Orden Asociada'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario al Comprar'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_TiendadeMagia.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='cliente',
            field=models.CharField(max_length=255, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='direccion_envio',
            field=models.TextField(verbose_name='Dirección de Envío'),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='fecha_orden',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Orden'),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='metodo_pago',
            field=models.CharField(choices=[('Tarjeta', 'Tarjeta de Crédito/Débito'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia Bancaria'), ('Cripto', 'Criptomoneda Arcana')], default='Tarjeta', max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Pociones', 'Pociones'), ('Artefactos', 'Artefactos'), ('Hechizos', 'Hechizos'), ('Ingredientes', 'Ingredientes'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Mágica'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Artículo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio (USD)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor Místico'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Inventario'),
        ),
    ]
