# Generated by Django 5.2.7 on 2025-11-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_TiendadeMagia', '0003_alter_producto_options_remove_producto_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
